import { requireAppContext } from "@/lib/auth/session";
import { canManageInventory } from "@/lib/auth/roles";
import { defaultForecastSettings } from "@/lib/operations/forecasting";
import { createClient } from "@/lib/supabase/server";
import { saveOperatingSettings, saveOrganizationProfile, saveWorkspaceSettings } from "./actions";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [query, context] = await Promise.all([searchParams, requireAppContext()]);
  const supabase = await createClient();
  const db = supabase as any;
  const [operatingResult, workspaceResult, orgResult] = await Promise.all([
    supabase.from("organization_operating_settings").select("*").eq("organization_id", context.organization.id).maybeSingle(),
    db.from("organization_settings").select("*").eq("organization_id", context.organization.id).maybeSingle(),
    db.from("organizations").select("name,website,timezone,country,currency").eq("id", context.organization.id).single(),
  ]);
  if (operatingResult.error) throw new Error(operatingResult.error.message);
  if (workspaceResult.error) throw new Error(workspaceResult.error.message);
  if (orgResult.error) throw new Error(orgResult.error.message);
  const operating = operatingResult.data;
  const workspace = workspaceResult.data;
  const org = orgResult.data;
  const manageable = canManageInventory(context.role);
  const admin = ["owner","admin"].includes(context.role);
  return <div className="product-page settings-page"><header className="product-page-header"><div><p>PLATFORM</p><h1>Settings</h1><span>Workspace identity, deterministic operating thresholds, notifications, and value measurement.</span></div></header>{query.saved && <p className="product-alert success">Operating settings saved.</p>}{query.error && <p className="product-alert error">{query.error}</p>}
    <section className="settings-card"><header><small>WORKSPACE</small><h2>Organization profile</h2><p>Core workspace identity used throughout Actnivo.</p></header><form action={saveOrganizationProfile}><label>Workspace name<input name="name" defaultValue={org.name} disabled={!admin} required/></label><label>Website<input name="website" defaultValue={org.website ?? ""} disabled={!admin} placeholder="https://example.com"/></label><label>Timezone<input name="timezone" defaultValue={org.timezone} disabled={!admin} required/></label><label>Country<span>{org.country}</span></label><label>Currency<span>{org.currency}</span></label>{admin ? <button className="saas-primary" type="submit">Save workspace profile</button> : <p>Your workspace role can view but not change this profile.</p>}</form></section>
    <section className="settings-card"><header><small>FORECASTING POLICY</small><h2>Stockout protection</h2><p>These values are stored per organization and copied into every forecast calculation for audit.</p></header><form action={saveOperatingSettings}><label>Replenishment lead time<span>Days required for replenishment to arrive.</span><input type="number" name="replenishment_lead_time_days" min="0" max="365" defaultValue={operating?.replenishment_lead_time_days ?? defaultForecastSettings.leadTimeDays} disabled={!manageable} required /></label><label>Safety days<span>Extra coverage Actnivo protects beyond lead time.</span><input type="number" name="safety_days" min="0" max="365" defaultValue={operating?.safety_days ?? defaultForecastSettings.safetyDays} disabled={!manageable} required /></label><label>Minimum safety stock<span>Absolute units protected at every source.</span><input type="number" name="minimum_safety_stock" min="0" max="1000000" defaultValue={operating?.minimum_safety_stock ?? defaultForecastSettings.minimumSafetyStock} disabled={!manageable} required /></label><label>Target days of cover<span>Coverage a source must retain before transfer.</span><input type="number" name="target_days_of_cover" min="1" max="365" defaultValue={operating?.target_days_of_cover ?? defaultForecastSettings.targetDaysOfCover} disabled={!manageable} required /></label>{manageable ? <button className="saas-primary" type="submit">Save operating policy</button> : <p>Your workspace role can view but not change this policy.</p>}</form></section>
    <section className="settings-card"><header><small>DECISION POLICY</small><h2>Risk & value settings</h2><p>Defaults for operational prioritization and ROI readiness. Autopilot can still override thresholds per workflow.</p></header><form action={saveWorkspaceSettings}><label>Minimum revenue risk<span>Default ₹ threshold for prioritized issues.</span><input type="number" name="default_risk_threshold" min="0" step="1" defaultValue={Number(workspace?.default_risk_threshold ?? 25000)} disabled={!admin}/></label><label>Minimum confidence %<span>Default confidence threshold for automated preparation.</span><input type="number" name="default_confidence_threshold" min="0" max="100" step="1" defaultValue={Math.round(Number(workspace?.default_confidence_threshold ?? .85) * 100)} disabled={!admin}/></label><label>Monthly Actnivo cost<span>Used only for transparent ROI readiness; never inferred.</span><input type="number" name="monthly_software_cost" min="0" step="1" defaultValue={Number(workspace?.monthly_software_cost ?? 0)} disabled={!admin}/></label><label><input type="checkbox" name="notify_critical_issues" defaultChecked={workspace?.notify_critical_issues ?? true} disabled={!admin}/> Critical issue notifications</label><label><input type="checkbox" name="notify_action_approvals" defaultChecked={workspace?.notify_action_approvals ?? true} disabled={!admin}/> Action approval notifications</label><label><input type="checkbox" name="notify_verification_failures" defaultChecked={workspace?.notify_verification_failures ?? true} disabled={!admin}/> Verification failure notifications</label>{admin ? <button className="saas-primary" type="submit">Save workspace settings</button> : <p>Only owners and admins can change these settings.</p>}</form></section>
  </div>;
}
