import Link from "next/link";
import { requireAppContext } from "@/lib/auth/session";
import { canManageInventory } from "@/lib/auth/roles";
import { createClient } from "@/lib/supabase/server";
import { getReturnsRtoWorkspace } from "@/lib/data/returns-rto";
import { refreshReturnsRtoIntelligence } from "./actions";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
const rowStyle={display:"grid",gridTemplateColumns:"1.3fr .7fr .8fr .8fr .8fr .5fr",gap:12,alignItems:"center",padding:"12px 24px",borderBottom:"1px solid var(--border)",textDecoration:"none",color:"var(--text-secondary)",fontSize:10} as const;
export default async function ReturnsRtoPage({searchParams}:{searchParams:Promise<{imported?:string;scan?:string;created?:string;resolved?:string;error?:string}>}){
  const [query,context]=await Promise.all([searchParams,requireAppContext()]);const supabase=await createClient();const data=await getReturnsRtoWorkspace(supabase as any,context.organization.id);
  return <div className="product-page"><header className="product-page-header"><div><p>OPERATIONS</p><h1>Returns & RTO</h1><span>Reverse-logistics health, refund exposure and RTO loss patterns.</span></div><div style={{display:"flex",gap:10}}><Link className="saas-primary" href="/app/returns-rto/import">Import return/RTO file</Link>{canManageInventory(context.role)&&<form action={refreshReturnsRtoIntelligence}><button type="submit">Refresh intelligence</button></form>}</div></header>
  {query.imported&&<p className="product-alert success">Imported {query.imported} return/RTO records.</p>}{query.scan&&<p className="product-alert success">Scanned {query.scan} records · {query.created??0} issues created · {query.resolved??0} resolved.</p>}{query.error&&<p className="product-alert error">{query.error}</p>}
  <section className="saas-metrics"><article><small>ACTIVE CASES</small><strong>{data.summary.active}</strong><p>{data.summary.total} total</p></article><article><small>CASH TIED UP</small><strong>{money.format(data.summary.cashTiedUp)}</strong><p>Open refund amount</p></article><article><small>RTO</small><strong>{data.summary.rto}</strong><p>{data.summary.returns} customer returns</p></article><article><small>EXCEPTIONS</small><strong>{data.summary.exceptions}</strong><p>Need operator attention</p></article><article><small>REVERSE COST</small><strong>{money.format(data.summary.reverseCost)}</strong><p>Recorded logistics cost</p></article></section>
  <div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:18,marginTop:18}}><section className="product-card"><header><div><small>REVERSE LOGISTICS</small><h2>Return & RTO queue</h2></div><span>{data.rows.length} records</span></header>{data.rows.length?<div className="simple-table"><div className="simple-table-head" style={{gridTemplateColumns:"1.3fr .7fr .8fr .8fr .8fr .5fr"}}><span>Case</span><span>Kind</span><span>Status</span><span>Refund</span><span>Cost</span><span>Risk</span></div>{data.rows.map((row:any)=><Link key={row.id} href={`/app/returns-rto/${row.id}`} style={rowStyle}><span><strong>{row.external_return_id}</strong><small>{row.order?.external_order_id??"Order"}</small></span><span>{row.kind}</span><span>{String(row.status).replaceAll("_"," ")}</span><span>{money.format(Number(row.refund_amount??0))}</span><span>{money.format(Number(row.reverse_logistics_cost??0))}</span><span>{row.exception?<strong>{row.exception.type.replaceAll("_"," ")}</strong>:"Healthy"}</span></Link>)}</div>:<div className="product-empty"><span>↩</span><h3>No return/RTO data yet.</h3><p>Import a bootstrap file or connect an OMS later.</p></div>}</section>
  <aside className="product-card"><header><div><small>LOSS PATTERNS</small><h2>Top SKUs</h2></div></header><div style={{padding:20,display:"grid",gap:14}}>{data.topLossSkus.length?data.topLossSkus.map((item:any)=><div key={item.sku}><strong>{item.sku}</strong><p>{item.product} · {item.count} cases · {money.format(item.value)}</p></div>):<p>No loss patterns yet.</p>}<hr/><small>CHANNEL RTO RATE</small>{data.channelPatterns.slice(0,4).map((item:any)=><div key={item.channel}><strong>{String(item.channel).replaceAll("_"," ")}</strong><p>{Math.round(item.rtoRate*100)}% of recorded reverse-logistics cases are RTO</p></div>)}</div></aside></div></div>;
}
